baseURL = "https://juhye-m.github.io/ps70/"
languageCode = "en-us"
title = "JuHye Mun"
theme = "stack"

[params]
  [params.defaultImage]
    [params.defaultImage.opengraph]
      enabled = false
      local = true

  [params.sidebar]
    emoji = "ðŸ‘¾"
    subtitle = "Blog for PS70"
    [params.sidebar.avatar]
      local = true
      src = "img/avatar.jpg"

[menu]
    [[menu.main]]
        identifier = "home"
        name = "Home"
        url = ""
        weight = -100
        pre = "home"
    [[menu.main]]
        identifier = "about-cn"
        name = "About"
        url = "about"
        weight = -90
        pre = "user"